config/routes.rb
DemoApp1::Application.routes.draw do

   root 'home#index'
   get '/user' => 'home#new'
   post '/users' => 'home#create'
   get '/users' => 'home#show'

  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def new
		@user = User.new
	end

	def create 
		@user = User.new(user_params)
		if @user.save
			render :json => @user
		else
			redirect_to 'root_url'
		end
	end

	def show
		@users = User.all
		render :json => @users
	end

	private
	def user_params
		params.require(:user).permit(:name, :address) if params[:user]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h2>Hey, this is a demo app</h2>
<%= link_to "Next", user_path %>
<%= link_to "Show users", users_path %>

app/views/home/new.html.erb
<%= form_for @user do |f| %>
User name:<%= f.text_field :name %>
Address:<%= f.text_field :address %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>